import image1 from './images/image_1.png';
import image2 from './images/image_2.png';
import image3 from './images/image_3.png';
import image4 from './images/image_4.png';

const clothes = [
  {
    id: 1,
    title: 'MACACÃO FEMININO MARIA FILO SOBREPOSIÇÃO',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: 'VERÃO 2022',
    image: image1,
  },
  {
    id: 2,
    title: 'REGATA FEMININA DE TRICOT COM OMBREIRA',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: '20% OFF',
    image: image2,
  },
  {
    id: 3,
    title: 'BLUSA FEMININA SILK MERCI LIOCEL',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: '',
    image: image3,
  },
  {
    id: 4,
    title: 'BLAZER FEMININO LIOCEL PUNHO',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: 'LANÇAMENTO',
    image: image4,
  },
  {
    id: 5,
    title: 'BLUSA FEMININA SILK MERCI LIOCEL',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: '',
    image: image3,
  },
  {
    id: 6,
    title: 'REGATA FEMININA DE TRICOT COM OMBREIRA',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: '20% OFF',
    image: image2,
  },
  {
    id: 7,
    title: 'BLAZER FEMININO LIOCEL PUNHO',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: 'LANÇAMENTO',
    image: image4,
  },
  {
    id: 8,
    title: 'MACACÃO FEMININO MARIA FILO SOBREPOSIÇÃO',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: 'VERÃO 2022',
    image: image1,
  },
  {
    id: 9,
    title: 'BLUSA FEMININA SILK MERCI LIOCEL',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: '',
    image: image3,
  },
  {
    id: 10,
    title: 'BLAZER FEMININO LIOCEL PUNHO',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: 'LANÇAMENTO',
    image: image4,
  },
  {
    id: 11,
    title: 'REGATA FEMININA DE TRICOT COM OMBREIRA',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: '20% OFF',
    image: image2,
  },
  {
    id: 12,
    title: 'MACACÃO FEMININO MARIA FILO SOBREPOSIÇÃO',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: 'VERÃO 2022',
    image: image1,
  },
  {
    id: 13,
    title: 'BLAZER FEMININO LIOCEL PUNHO',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: 'LANÇAMENTO',
    image: image4,
  },
  {
    id: 14,
    title: 'BLUSA FEMININA SILK MERCI LIOCEL',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: '',
    image: image3,
  },
  {
    id: 15,
    title: 'MACACÃO FEMININO MARIA FILO SOBREPOSIÇÃO',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: 'VERÃO 2022',
    image: image1,
  },
  {
    id: 16,
    title: 'REGATA FEMININA DE TRICOT COM OMBREIRA',
    price: 759.00,
    amount: 0,
    instalments: '12 X R$ 63,25',
    tag: '20% OFF',
    image: image2,
  },
];

export default clothes;
